### ISSUE TITLE
Request for "VI for DPMM" note

### ISSUE THREAD

**Issue by ckm4514** [pokan975/Gibbs-Variational-Inference#1]
Hi!
First of all, thanks for uploading such clean and useful code regarding VI for DPMM.
I am trying to apply your codes in my problem(it is about VI for DPMM), but I am having trouble on deriving updating equations and ELBO equations..
Can you share the "VI for DPMM" note(I saw you mentioning this note in VI_DPMM_func code) that contains such equations?
Thanks again !! :)

**Comment by pokan975** [comment]
Thanks for your comment, I just uploaded the note "VI for DPMM", it's in mht format, you can open it using IE browser. It includes all equations for q updates and ELBO computation. There is still a small gap between the equations and code, but it should be comprehensible.
